<?php

namespace Troiswa\PublicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */


#Repository pour stocker requetes + produit find et find all. Accessible de partout
class FilmRepository extends EntityRepository
{

public function getNbFilmByCategorie(){

    $req = $this -> getEntityManager() -> createQuery(
        "SELECT COUNT(f.id) as nbFilms, c.titre
        FROM TroiswaPublicBundle:Film f
        LEFT JOIN f. categorie c
        GROUP BY c.id "
        );

    return $req -> getResult();
        }







}





